apiVersion: v1
kind: Service
metadata:
  name: java-webapp-service
  labels:
    app: java-webapp
spec:
  selector:
    app: java-webapp
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: LoadBalancer

