apiVersion: apps/v1
kind: Deployment
metadata:
  name: java-webapp
  labels:
    app: java-webapp
spec:
  replicas: 3
  selector:
    matchLabels:
      app: java-webapp
  template:
    metadata:
      labels:
        app: java-webapp
    spec:
      containers:
        - name: java-webapp
          image: yogi1433/java-app:latest # Replace with your image
          imagePullPolicy: Always
          ports:
            - containerPort: 8080

